Added Favicon image 7pm-1
ucsb-cs156-w21/proj-ucsb-cs-las pull request #108
Opened 2021-02-17 03:53 UTC by vrobot

Resolve #105 
Added favicon image.

2021-02-24 02:59 UTC, pconrad requested changes

2021-02-24 02:59 UTC, pconrad commented on javascript/public/manifest.json
> +{"name":"","short_name":"","icons":[{"src":"/android-chrome-192x192.png","sizes":"192x192","type":"image/png"},{"src":"/android-chrome-512x512.png","sizes":"512x512","type":"image/png"}],"theme_color
I wonder if, instead of "name" we might put `"Mapache Search"`

And instead of `"short_name"` we might put `"mapache"`

2021-02-24 02:59 UTC, pconrad commented on javascript/public/manifest.json
> +{"name":"","short_name":"","icons":[{"src":"/android-chrome-192x192.png","sizes":"192x192","type":"image/png"},{"src":"/android-chrome-512x512.png","sizes":"512x512","type":"image/png"}],"theme_color
You may also want to reformat the JSON.  

Your editor might have a feature to do this automatically.  If it's VSCode, you can install a formatter for JSON files as an Extension.

Or you could do it manually.  Compare how the old manifest.json was formatted.

2021-02-24 03:02 UTC, ethanmeade approved these changes
Everything seems to be in order.

2021-02-24 10:16 UTC, andrewhlu commented
Please address @pconrad's changes above, re-review it within your team, then request the staff for a review again.

2021-02-24 21:18 UTC, yusong-yan approved these changes
LGTM

2021-02-24 21:30 UTC, pconrad commented on javascript/public/manifest.json
> +{"name":"","short_name":"","icons":[{"src":"/android-chrome-192x192.png","sizes":"192x192","type":"image/png"},{"src":"/android-chrome-512x512.png","sizes":"512x512","type":"image/png"}],"theme_color
Ooops.. my bad, I should have "UCSB CS LAs" for name, and "CS LAs" for short name.

2021-02-26 19:51 UTC, pconrad approved these changes
LGTM

2021-02-26 19:53 UTC, pconrad approved these changes
LGTM

2021-02-26 19:54 UTC, pconrad commented
> LGTM

Hi @yusong-yan ... You made a "comment" LGTM, but for that to trigger the reviewer, you need to do it "as an approving code review".

Here's what that looks like: 

![LGTM-Code-Review](https://user-images.githubusercontent.com/1119017/109348415-592c4d80-7829-11eb-84ee-f598c53a8e3b.gif)

2021-03-01 06:17 UTC, ethanmeade approved these changes
LGTM

2021-03-01 21:29 UTC, yusong-yan approved these changes

2021-03-01 21:42 UTC, merged