6pm 1 office hours table
ucsb-cs156-w21/proj-ucsb-cs-las pull request #134
Opened 2021-03-01 21:42 UTC by carsoncoley

Make office hours table rows alternate color; 6pm 1 office hours table

2021-03-01 21:50 UTC, LeoJr99 approved these changes

2021-03-01 21:50 UTC, LeoJr99 commented on javascript/src/main/components/OfficeHours/OfficeHourTable.js
> +            text:  "Delete",
Everything looks good. Maybe delete the white space in line 40 to reduce the amount of changes made

2021-03-03 01:26 UTC, mara-downing requested changes
I agree with Leo, everything looks good but you should delete the space before "Delete" for consistency.

2021-03-03 02:12 UTC, btk5h requested changes

2021-03-03 02:12 UTC, btk5h commented on javascript/src/main/components/OfficeHours/OfficeHourTable.js
> +        <BootstrapTable keyField='id' data={officeHours} columns={columns} striped={true}/>
The `={true}` is redundant in React. If you change this to `striped`, React will implicitly treat this as `striped={true}`.
```suggestion
        <BootstrapTable keyField='id' data={officeHours} columns={columns} striped />
```

2021-03-03 02:27 UTC, LeoJr99 approved these changes
LGTM

2021-03-03 02:28 UTC, LeoJr99 approved these changes
LGTM

2021-03-03 02:33 UTC, btk5h approved these changes

2021-03-03 02:43 UTC, merged