6pm 1 office hours time format
ucsb-cs156-w21/proj-ucsb-cs-las pull request #140
Opened 2021-03-04 21:57 UTC by namabilly

Implemented the **general** form validity check in front end. Added the time format check with regex. Now we are skipping NewOfficeHour tests that assume no validity check, which are incompatible with current PR. The functions should still work properly.

2021-03-04 22:36 UTC, btk5h requested changes
Do you have tests for `OfficeHourForm`? Skipping the `NewOfficeHours` tests is okay if it would require a lot of refactoring to do properly, but you should at least be able to write tests for the `OfficeHourForm` component.

2021-03-05 00:49 UTC, namabilly reviewed
Now `NewOfficeHour.test.js` runs properly, no need to skip

2021-03-05 00:53 UTC, justinsurmani approved these changes
LGTM

2021-03-07 18:52 UTC, btk5h approved these changes

2021-03-07 18:55 UTC, merged