6pm 1 CSV Upload for Tutor
ucsb-cs156-w21/proj-ucsb-cs-las pull request #168
Opened 2021-03-10 19:52 UTC by LeoJr99

PR resolved #123.  This PR adds a button that allows for a csv upload for the tutor table

2021-03-10 23:43 UTC, moisesgtz reviewed
LGTM

2021-03-10 23:45 UTC, moisesgtz submitted a review, later dismissed
LGTM

2021-03-11 21:31 UTC, btk5h requested changes

2021-03-11 21:31 UTC, btk5h commented on src/test/java/edu/ucsb/ucsbcslas/controllers/TutorControllerTests.java
> +  @MockBean
`Reader` isn't a spring bean, consider using `Mock` here instead.

2021-03-11 21:31 UTC, btk5h commented on javascript/src/main/components/Tutor/TutorCSVButton.js
> +                    console.log("Caught error");
If there's an error here, maybe we should display a toast to the user?

2021-03-11 22:48 UTC, btk5h approved these changes

2021-03-11 22:50 UTC, justinsurmani approved these changes
LGTM

2021-03-11 22:51 UTC, merged